/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.lyuben.gui;

import com.github.lyuben.bridge.Astyanax;
import com.netflix.astyanax.Keyspace;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author lyubentodorov
 */
public class NewMessageForm extends javax.swing.JFrame {

    private Keyspace keyspace;
    private String _USERNAME_ = "";
    
    public NewMessageForm(Keyspace keyspace, String username) {
        this.keyspace = keyspace;
        this._USERNAME_ = username;
        initComponents();
        setupFrame();
    }
    
    //Constructor for replying to a message
    public NewMessageForm(Keyspace keyspace, String username, String sender, String subject) {
        this.keyspace = keyspace;
        this._USERNAME_ = username;
        initComponents();
        jTextField_NewMessage_To.setText(sender);
        jTextField_NewMessage_Title.setText(subject);
        setupFrame();
    }


    
    // This method is called from within the constructor to initialize the form.
    // WARNING: Do NOT modify this code. The content of this method is always
    // regenerated by the Form Editor.
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField_NewMessage_To = new javax.swing.JTextField();
        jLabel_To = new javax.swing.JLabel();
        jLabel_Subject = new javax.swing.JLabel();
        jTextField_NewMessage_Title = new javax.swing.JTextField();
        jButton_Send = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_NewMessage_Body = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_To.setText("To");

        jLabel_Subject.setText("Subject");

        jButton_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/lyuben/img/send.png")));
        jButton_Send.setText("Send");
        jButton_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel_To)
                            .add(jLabel_Subject))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField_NewMessage_To)
                            .add(jTextField_NewMessage_Title)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton_Send, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel_To)
                    .add(jTextField_NewMessage_To, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel_Subject)
                    .add(jTextField_NewMessage_Title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton_Send)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_NewMessage_Body.setColumns(20);
        jTextArea_NewMessage_Body.setLineWrap(true);
        jTextArea_NewMessage_Body.setRows(5);
        jTextArea_NewMessage_Body.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea_NewMessage_Body);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    //
    //
    private void jButton_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendActionPerformed
        try {
            // Insert the email into the db
            Astyanax.insertEmail(keyspace, _USERNAME_, Arrays.asList(
                jTextField_NewMessage_To.getText(),     //receiver
                jTextField_NewMessage_Title.getText(),  //subject
                jTextArea_NewMessage_Body.getText()));  //body
            
            JOptionPane.showMessageDialog(this, "Message has been sent to " + 
                    jTextField_NewMessage_To.getText() + "!\nFrame will now close."
                , "All good over here!", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "A problem occured!"
                , "Error sending email", JOptionPane.ERROR_MESSAGE);
        }
        
        destroyFrame();
    }//GEN-LAST:event_jButton_SendActionPerformed

    
    
    // Sets up frame related configs
    // @void
    //
    private void setupFrame(){
        //this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle("Cassandra SeceMail - Send message");
        this.setVisible(true);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent ev) {
                destroyFrame();
            }
        });
    }
    
    
    
    // Closes the frame and redisplays login frame.
    //
    //
    private void destroyFrame(){
        this.setVisible(false);
        this.dispose();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Send;
    private javax.swing.JLabel jLabel_Subject;
    private javax.swing.JLabel jLabel_To;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_NewMessage_Body;
    private javax.swing.JTextField jTextField_NewMessage_Title;
    private javax.swing.JTextField jTextField_NewMessage_To;
    // End of variables declaration//GEN-END:variables
}
